# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.intent_list_response import IntentListResponse

class TestIntentListResponse(unittest.TestCase):
    """IntentListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntentListResponse:
        """Test IntentListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntentListResponse`
        """
        model = IntentListResponse()
        if include_optional:
            return IntentListResponse(
                items = [
                    openapi_client.models.intent.Intent(
                        id = '', 
                        key = 'users.list', 
                        title = 'List users', 
                        description = '', 
                        version = '1.0.0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = ''
            )
        else:
            return IntentListResponse(
                items = [
                    openapi_client.models.intent.Intent(
                        id = '', 
                        key = 'users.list', 
                        title = 'List users', 
                        description = '', 
                        version = '1.0.0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testIntentListResponse(self):
        """Test IntentListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
