# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.signup_request import SignupRequest

class TestSignupRequest(unittest.TestCase):
    """SignupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignupRequest:
        """Test SignupRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignupRequest`
        """
        model = SignupRequest()
        if include_optional:
            return SignupRequest(
                email = '',
                password = '01234567',
                name = ''
            )
        else:
            return SignupRequest(
                email = '',
                password = '01234567',
        )
        """

    def testSignupRequest(self):
        """Test SignupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
