# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.intents_api import IntentsApi


class TestIntentsApi(unittest.TestCase):
    """IntentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_intent(self) -> None:
        """Test case for create_intent

        Create a new intent
        """
        pass

    def test_get_intent_by_id(self) -> None:
        """Test case for get_intent_by_id

        Get intent by id
        """
        pass

    def test_list_intents(self) -> None:
        """Test case for list_intents

        List intents
        """
        pass


if __name__ == '__main__':
    unittest.main()
