# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_password_reset_request200_response import AuthPasswordResetRequest200Response

class TestAuthPasswordResetRequest200Response(unittest.TestCase):
    """AuthPasswordResetRequest200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPasswordResetRequest200Response:
        """Test AuthPasswordResetRequest200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPasswordResetRequest200Response`
        """
        model = AuthPasswordResetRequest200Response()
        if include_optional:
            return AuthPasswordResetRequest200Response(
                message = '',
                reset_token = '',
                expires_in = 56
            )
        else:
            return AuthPasswordResetRequest200Response(
        )
        """

    def testAuthPasswordResetRequest200Response(self):
        """Test AuthPasswordResetRequest200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
