# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scope import Scope

class TestScope(unittest.TestCase):
    """Scope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Scope:
        """Test Scope
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Scope`
        """
        model = Scope()
        if include_optional:
            return Scope(
                id = 56,
                org_id = 56,
                name = '',
                type = 'user',
                verification_status = 'unverified'
            )
        else:
            return Scope(
                id = 56,
                name = '',
                type = 'user',
                verification_status = 'unverified',
        )
        """

    def testScope(self):
        """Test Scope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
