# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.scopes_api import ScopesApi


class TestScopesApi(unittest.TestCase):
    """ScopesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScopesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_scopes_get(self) -> None:
        """Test case for v1_scopes_get

        List scopes and verification posture
        """
        pass

    def test_v1_scopes_name_get(self) -> None:
        """Test case for v1_scopes_name_get

        Get scope by name
        """
        pass

    def test_v1_scopes_name_verification_put(self) -> None:
        """Test case for v1_scopes_name_verification_put

        Update scope verification status (admin)
        """
        pass

    def test_v1_scopes_post(self) -> None:
        """Test case for v1_scopes_post

        Create scope with trust metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
