# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_check(self) -> None:
        """Test case for health_check

        Health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
