# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.registry_index_api import RegistryIndexApi


class TestRegistryIndexApi(unittest.TestCase):
    """RegistryIndexApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistryIndexApi()

    def tearDown(self) -> None:
        pass

    def test_v1_index_changes_get(self) -> None:
        """Test case for v1_index_changes_get

        Incremental index change feed
        """
        pass

    def test_v1_index_pkg_scope_name_get(self) -> None:
        """Test case for v1_index_pkg_scope_name_get

        Compact package metadata for clients
        """
        pass


if __name__ == '__main__':
    unittest.main()
