# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.registry_governance_api import RegistryGovernanceApi


class TestRegistryGovernanceApi(unittest.TestCase):
    """RegistryGovernanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistryGovernanceApi()

    def tearDown(self) -> None:
        pass

    def test_v1_packages_scope_name_tags_get(self) -> None:
        """Test case for v1_packages_scope_name_tags_get

        List dist-tags for a package
        """
        pass

    def test_v1_packages_scope_name_tags_tag_put(self) -> None:
        """Test case for v1_packages_scope_name_tags_tag_put

        Set dist-tag target version (admin)
        """
        pass

    def test_v1_packages_scope_name_versions_version_deprecate_put(self) -> None:
        """Test case for v1_packages_scope_name_versions_version_deprecate_put

        Deprecate or clear deprecation for a version
        """
        pass

    def test_v1_packages_scope_name_versions_version_quarantine_put(self) -> None:
        """Test case for v1_packages_scope_name_versions_version_quarantine_put

        Quarantine a version (admin)
        """
        pass

    def test_v1_packages_scope_name_versions_version_unquarantine_put(self) -> None:
        """Test case for v1_packages_scope_name_versions_version_unquarantine_put

        Remove quarantine from a version (admin)
        """
        pass


if __name__ == '__main__':
    unittest.main()
