# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_login(self) -> None:
        """Test case for auth_login

        Login with email and password
        """
        pass


if __name__ == '__main__':
    unittest.main()
