# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.package_list_item import PackageListItem

class TestPackageListItem(unittest.TestCase):
    """PackageListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageListItem:
        """Test PackageListItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageListItem`
        """
        model = PackageListItem()
        if include_optional:
            return PackageListItem(
                id = 56,
                scope = '',
                name = '',
                visibility = '',
                description = ''
            )
        else:
            return PackageListItem(
                id = 56,
                scope = '',
                name = '',
        )
        """

    def testPackageListItem(self):
        """Test PackageListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
