# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_logout_request import AuthLogoutRequest

class TestAuthLogoutRequest(unittest.TestCase):
    """AuthLogoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthLogoutRequest:
        """Test AuthLogoutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthLogoutRequest`
        """
        model = AuthLogoutRequest()
        if include_optional:
            return AuthLogoutRequest(
                refresh_token = ''
            )
        else:
            return AuthLogoutRequest(
        )
        """

    def testAuthLogoutRequest(self):
        """Test AuthLogoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
