# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.intent_create_request import IntentCreateRequest

class TestIntentCreateRequest(unittest.TestCase):
    """IntentCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntentCreateRequest:
        """Test IntentCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntentCreateRequest`
        """
        model = IntentCreateRequest()
        if include_optional:
            return IntentCreateRequest(
                key = '',
                title = '',
                description = ''
            )
        else:
            return IntentCreateRequest(
                key = '',
                title = '',
        )
        """

    def testIntentCreateRequest(self):
        """Test IntentCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
