# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.packages_list_response import PackagesListResponse

class TestPackagesListResponse(unittest.TestCase):
    """PackagesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackagesListResponse:
        """Test PackagesListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackagesListResponse`
        """
        model = PackagesListResponse()
        if include_optional:
            return PackagesListResponse(
                items = [
                    openapi_client.models.package_list_item.PackageListItem(
                        id = 56, 
                        scope = '', 
                        name = '', 
                        visibility = '', 
                        description = '', )
                    ],
                pagination = openapi_client.models.packages_pagination.PackagesPagination(
                    total = 56, 
                    limit = 56, 
                    offset = 56, )
            )
        else:
            return PackagesListResponse(
                items = [
                    openapi_client.models.package_list_item.PackageListItem(
                        id = 56, 
                        scope = '', 
                        name = '', 
                        visibility = '', 
                        description = '', )
                    ],
                pagination = openapi_client.models.packages_pagination.PackagesPagination(
                    total = 56, 
                    limit = 56, 
                    offset = 56, ),
        )
        """

    def testPackagesListResponse(self):
        """Test PackagesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
