# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_tokens import AuthTokens

class TestAuthTokens(unittest.TestCase):
    """AuthTokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthTokens:
        """Test AuthTokens
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthTokens`
        """
        model = AuthTokens()
        if include_optional:
            return AuthTokens(
                access_token = '',
                refresh_token = '',
                expires_in = 56
            )
        else:
            return AuthTokens(
                access_token = '',
                refresh_token = '',
                expires_in = 56,
        )
        """

    def testAuthTokens(self):
        """Test AuthTokens"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
