# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_password_reset_confirm_request import AuthPasswordResetConfirmRequest

class TestAuthPasswordResetConfirmRequest(unittest.TestCase):
    """AuthPasswordResetConfirmRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthPasswordResetConfirmRequest:
        """Test AuthPasswordResetConfirmRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthPasswordResetConfirmRequest`
        """
        model = AuthPasswordResetConfirmRequest()
        if include_optional:
            return AuthPasswordResetConfirmRequest(
                token = '',
                new_password = '01234567'
            )
        else:
            return AuthPasswordResetConfirmRequest(
                token = '',
                new_password = '01234567',
        )
        """

    def testAuthPasswordResetConfirmRequest(self):
        """Test AuthPasswordResetConfirmRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
