# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.trusted_publishing_api import TrustedPublishingApi


class TestTrustedPublishingApi(unittest.TestCase):
    """TrustedPublishingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrustedPublishingApi()

    def tearDown(self) -> None:
        pass

    def test_v1_packages_scope_name_versions_version_provenance_get(self) -> None:
        """Test case for v1_packages_scope_name_versions_version_provenance_get

        Get provenance for a package version
        """
        pass

    def test_v1_packages_scope_name_versions_version_provenance_put(self) -> None:
        """Test case for v1_packages_scope_name_versions_version_provenance_put

        Upsert provenance for a package version
        """
        pass

    def test_v1_publish_oidc_exchange_post(self) -> None:
        """Test case for v1_publish_oidc_exchange_post

        Exchange trusted OIDC identity for short-lived publish token
        """
        pass


if __name__ == '__main__':
    unittest.main()
