# coding: utf-8

"""
    Intent API

    REST API for the Intent Ecosystem.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_session_response import AuthSessionResponse

class TestAuthSessionResponse(unittest.TestCase):
    """AuthSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthSessionResponse:
        """Test AuthSessionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthSessionResponse`
        """
        model = AuthSessionResponse()
        if include_optional:
            return AuthSessionResponse(
                user = openapi_client.models.user.User(
                    id = 56, 
                    email = '', 
                    name = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                access_token = '',
                refresh_token = '',
                expires_in = 56
            )
        else:
            return AuthSessionResponse(
                user = openapi_client.models.user.User(
                    id = 56, 
                    email = '', 
                    name = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                access_token = '',
                refresh_token = '',
                expires_in = 56,
        )
        """

    def testAuthSessionResponse(self):
        """Test AuthSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
