# coding: utf-8

# flake8: noqa
"""
    Intent API

    REST API for the Intent Ecosystem (source of truth for clients and SDKs).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.auth_tokens import AuthTokens
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.health_response import HealthResponse
from openapi_client.models.intent import Intent
from openapi_client.models.intent_create_request import IntentCreateRequest
from openapi_client.models.intent_list_response import IntentListResponse
from openapi_client.models.login_request import LoginRequest
from openapi_client.models.user import User
